# Generated by Django 5.2.9 on 2026-01-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='owner_contacts',
            field=models.TextField(verbose_name='Контактная информация владельца'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='sim_slots',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Количество SIM-карт'),
        ),
    ]
